package com.otr.dbms.controller;

import com.otr.dbms.db.DAO;
import com.otr.dbms.entity.PatientInfoEntity;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

public class WriteController {

    private DAO dao = new DAO();
    private List<TextField> allTextFields = new ArrayList<>();

    @FXML private TextField Name;
    @FXML private TextField SubjectCode;
    @FXML private TextField IDNumber;
    @FXML private TextField Phone;
    @FXML private TextField DateTest;
    @FXML private TextField Birthdate;
    @FXML private TextField Age;
    @FXML private TextField Gr;
    @FXML private TextField Sex;
    @FXML private TextField Bac;
    @FXML private TextField Edu;
    @FXML private TextField EduY;
    @FXML private TextField MusEdu;
    @FXML private TextField MusEduY;
    @FXML private TextField Hand;
    @FXML private TextField Profession;
    @FXML private TextField CurrentWork;
    @FXML private TextField Intoxicant;
    @FXML private TextField Eye;
    @FXML private TextField Ear;
    @FXML private TextField InjuryWithFainting;
    @FXML private TextField Fainting;
    @FXML private TextField Neurologist;
    @FXML private TextField Psychiatrist;
    @FXML private TextField Depression;
    @FXML private TextField Hypertension;
    @FXML private TextField HeartAttack;
    @FXML private TextField CardiacArrest;
    @FXML private TextField CardiacInsuff;
    @FXML private TextField KidneysInsuff;
    @FXML private TextField LiverInsuff;
    @FXML private TextField Diabetes;
    @FXML private TextField Thyroid;
    @FXML private TextField Lungs;
    @FXML private TextField Neurodegeneration;
    @FXML private TextField OtherDisorders;
    @FXML private TextField Alco_now;
    @FXML private TextField Alco_pa;
    @FXML private TextField Drugs;
    @FXML private TextField AgeOnset;
    @FXML private TextField AgeDiagnosis;
    @FXML private TextField DiseaseDurationY;
    @FXML private TextField MemoryComplains;
    @FXML private TextField OtherCognitiveComplains;
    @FXML private TextField SideSymptOnSet;
    @FXML private TextField CurrentSympt;
    @FXML private TextField TK_MRI;
    @FXML private TextField AsymmsymptNow;
    @FXML private TextField MotPhenot;
    @FXML private TextField UPDRSDyskin_32_33_34_35;
    @FXML private TextField UPDRSMotFluct36_37_38_39;
    @FXML private TextField UPDRSFalling_13;
    @FXML private TextField Hallucination_2;
    @FXML private TextField HallucinationOnSetY;
    @FXML private TextField Medications;
    @FXML private TextField L_Dopaequiv;
    @FXML private TextField OtherTreatment;
    @FXML private TextField Surg;
    @FXML private TextField Surg_Desc;
    @FXML private TextField ADLON;
    @FXML private TextField ADLOFF;
    @FXML private TextField IADLON;
    @FXML private TextField IADLOFF;
    @FXML private TextField HAndYON;
    @FXML private TextField HAndYOFF;
    @FXML private TextField SchAndEngON;
    @FXML private TextField SchAndEngOFF;
    @FXML private TextField UPDRSON;
    @FXML private TextField UPDRSOFF;
    @FXML private TextField UPDRSION;
    @FXML private TextField UPDRSIOFF;
    @FXML private TextField UPDRSIION;
    @FXML private TextField UPDRSIIOFF;
    @FXML private TextField UPDRSIIION;
    @FXML private TextField UPDRSIIIOFF;
    @FXML private TextField UPDRS_Speech_5;
    @FXML private TextField UPDRS_Speech_18;
    @FXML private TextField UPDRS_FacialExpress_19;
    @FXML private TextField UPDRS_TremorRest_20;
    @FXML private TextField UPDRS_EssentialTremor_21;
    @FXML private TextField UPDRS_Ridigity_22;
    @FXML private TextField UPDRS_DigitMov23;
    @FXML private TextField UPDRSIII_HandMov_24;
    @FXML private TextField UPDRSRapidAlterHandMov_25;
    @FXML private TextField UPDRSLegAgility_26;
    @FXML private TextField UPDRSArisingChair_27;
    @FXML private TextField UPDRSPosture_28;
    @FXML private TextField UPDRS_PostureStab_29;
    @FXML private TextField UPDRS_Gait_30;
    @FXML private TextField UPDRSIII_Bradykinesia_31;
    @FXML private TextField Progression_PD;
    @FXML private TextField UMSARSI;
    @FXML private TextField UMSARSII;
    @FXML private TextField UMSARSIII_Orthostatic;
    @FXML private TextField UMSARSIV;
    @FXML private TextField UMSARSI_II;
    @FXML private TextField UMSARSISpeech_1;
    @FXML private TextField UMSARSIWalking_7;
    @FXML private TextField UMSARSIFalling_8;
    @FXML private TextField UMSARSII_Facialexpression_1;
    @FXML private TextField UMSARSIISpeech_2;
    @FXML private TextField UMSARSII_OcuMotDys_3;
    @FXML private TextField UMSARSII_TremRest_4;
    @FXML private TextField UMSARSII_ActTrem_5;
    @FXML private TextField UMSARSII_IncTone_6;
    @FXML private TextField UMSARSRapidAlterMov_Hands_7;
    @FXML private TextField UMSARSFingertaps_8;
    @FXML private TextField UMSARSLegAgility_9;
    @FXML private TextField UMSARSHeelknee_10;
    @FXML private TextField UMSARSArisingChair_11;
    @FXML private TextField UMSARSPosture_12;
    @FXML private TextField UMSARSBodysway_13;
    @FXML private TextField UMSARSGait_14;
    @FXML private TextField AttentionFactACE_III;
    @FXML private TextField MemFactACE_III;
    @FXML private TextField FluencyFactACE_III;
    @FXML private TextField LangFactACE_III;
    @FXML private TextField VisualFactACE_III;
    @FXML private TextField TotalACE_III;
    @FXML private TextField TotalMini_ACE_III;
    @FXML private TextField MMSE;
    @FXML private TextField FAB12;
    @FXML private TextField BDI13_14;
    @FXML private TextField GDS9_10;
    @FXML private TextField WAIS_RPicture;
    @FXML private TextField WAIS_RPictureCent;
    @FXML private TextField CVLT_1_5;
    @FXML private TextField CVLT_1_5Sten;
    @FXML private TextField CVLT_A_1;
    @FXML private TextField CVLT_A_1Sten;
    @FXML private TextField CVLT_A_5;
    @FXML private TextField CVLT_A_5Sten;
    @FXML private TextField CVLT_B;
    @FXML private TextField CVLT_BSten;
    @FXML private TextField CVLTSTM_Free;
    @FXML private TextField CVLTSTM_FreeSten;
    @FXML private TextField CVLTSTM_Cued;
    @FXML private TextField CVLTSTM_CuedSten;
    @FXML private TextField CVLTLTM_Free;
    @FXML private TextField CVLTLTM_FreeSten;
    @FXML private TextField CVLTLTM_Cued;
    @FXML private TextField CVLTLTM_CuedSten;
    @FXML private TextField CVLTSemCluster;
    @FXML private TextField CVLTSemClustSten;
    @FXML private TextField CVLTserialClust;
    @FXML private TextField CVLTserialClustSten;
    @FXML private TextField CVLTPercentCorrectI;
    @FXML private TextField CVLTPercentCorrectISten;
    @FXML private TextField CVLTPercentCorrectII;
    @FXML private TextField CVLTPercentCorrectIISten;
    @FXML private TextField CVLTPercentCorrectIII;
    @FXML private TextField CVLTPercentCorrectIIISten;
    @FXML private TextField CVLTagreeFactor;
    @FXML private TextField CVLTagreeFactorSten;
    @FXML private TextField CVLTPERS;
    @FXML private TextField PERSSten;
    @FXML private TextField CVLTintrusFree;
    @FXML private TextField CVLTintrusFreeSten;
    @FXML private TextField CVLTintrusCues;
    @FXML private TextField CVLTintrusCuesSten;
    @FXML private TextField CVLT_RecogTotal;
    @FXML private TextField CVLT_RecogTotalSten;
    @FXML private TextField CVLT_Differentiation;
    @FXML private TextField CVLT_DifferentiationSten;
    @FXML private TextField CVLT_ErrorRecog;
    @FXML private TextField CVLT_ErrorRecogSten;
    @FXML private TextField TMT_A;
    @FXML private TextField TMT_Acent;
    @FXML private TextField TMT_A_errors;
    @FXML private TextField TMT_B;
    @FXML private TextField TMT_Bcent;
    @FXML private TextField TMT_B_errors;
    @FXML private TextField Rythymtest_ABC;
    @FXML private TextField Rythymtest_ABCranga;
    @FXML private TextField TOL_TotalCorrect;
    @FXML private TextField TOL_TotalCorrectCent;
    @FXML private TextField TOL_TotalMoveScore;
    @FXML private TextField TOL_TotalMoveScoreCent;
    @FXML private TextField TOL_TotalInitTime;
    @FXML private TextField TOL_TotalInitTimeCent;
    @FXML private TextField TOL_TotalExecutTime;
    @FXML private TextField TOL_TotalExecutTimeCent;
    @FXML private TextField TOL_TotalTime;
    @FXML private TextField TOL_TotalTimeCent;
    @FXML private TextField FluencyKraw;
    @FXML private TextField FluencyAnimalsRaw;
    @FXML private TextField FluencySharpsRaw;
    @FXML private TextField BNTTotalScore;
    @FXML private TextField BNTCorrectPhonemCues;
    @FXML private TextField BNTCorrectSemantCues;
    @FXML private TextField BNTCorrectContextCues;
    @FXML private TextField BNTTotalTime;
    @FXML private TextField CLOX1Draw;
    @FXML private TextField CLOX2Copy;
    @FXML private TextField RBMTShortDelay;
    @FXML private TextField RBMTShortDelayCent;
    @FXML private TextField RBMTLongDelay;
    @FXML private TextField RBMTLongDelayCent;
    @FXML private TextField GONOGOProcentInCorrGO;
    @FXML private TextField GONOGOProcentInCorrNOGO;
    @FXML private TextField GONOGONrInCorrGO;
    @FXML private TextField GONOGONrInCorrNOGO;
    @FXML private TextField GONOGONrCorrectGO;
    @FXML private TextField GONOGONrCorrectNOGO;
    @FXML private TextField MeanResponseTimeCorrrectGO;
    @FXML private TextField ElevatorCountTotal;
    @FXML private TextField ElevatorCountTotalCent;
    @FXML private TextField ElevatorDistractTotal;
    @FXML private TextField ElevatorDistractTotalCent;
    @FXML private TextField WCSTLPP;
    @FXML private TextField WCSTLPO;
    @FXML private TextField WCSTLBO;
    @FXML private TextField WCST_LBOcent;
    @FXML private TextField WCSTPB;
    @FXML private TextField WCSTOP;
    @FXML private TextField WCSTOPcent;
    @FXML private TextField WCSTPOP;
    @FXML private TextField WCSTBP;
    @FXML private TextField WCSTBPcent;
    @FXML private TextField WCSTPBP;
    @FXML private TextField WCSTPBPcent;
    @FXML private TextField WCSTBN;
    @FXML private TextField WCSTBNcent;
    @FXML private TextField WCSTPBN;
    @FXML private TextField WCSTODP;
    @FXML private TextField WCSTPODP;
    @FXML private TextField WCSTPODPcent;
    @FXML private TextField WCSTLZK;
    @FXML private TextField WCSTPPMZ;
    @FXML private TextField WCSTPUN;
    @FXML private TextField WCSTUU;
    @FXML private TextField Similar_WAISTotal;
    @FXML private TextField Similar_WAISCent;
    @FXML private TextField WAIS_Info;
    @FXML private TextField WAIS_Info_Cent;
    @FXML private TextField WAIS_DigitSpan;
    @FXML private TextField WAIS_DigitSpan_Cent;
    @FXML private TextField MirrorTotalTime;
    @FXML private TextField MirrorMeanTime;
    @FXML private TextField MirrorCorrectScore;
    @FXML private TextField MirrorErrors;
    @FXML private TextField MirrorCorrectedErrors;
    @FXML private TextField JLOCorrect;
    @FXML private TextField JLOWP;
    @FXML private TextField JLOcent;

    @FXML public void initialize() {
        dao.setup();
        fillTextFieldCollection();
    }

    public void create(){
        if (idNumberVerification()) {
            try {
                dao.create(getPatient());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    public void clean(){
        for (TextField textField : allTextFields){
            textField.setText("");
        }
    }

    private void fillTextFieldCollection(){
        allTextFields.add(Name);
        allTextFields.add(SubjectCode);
        allTextFields.add(IDNumber);
        allTextFields.add(Phone);
        allTextFields.add(DateTest);
        allTextFields.add(Birthdate);
        allTextFields.add(Age);
        allTextFields.add(Gr);
        allTextFields.add(Sex);
        allTextFields.add(Bac);
        allTextFields.add(Edu);
        allTextFields.add(EduY);
        allTextFields.add(MusEdu);
        allTextFields.add(MusEduY);
        allTextFields.add(Hand);
        allTextFields.add(Profession);
        allTextFields.add(CurrentWork);
        allTextFields.add(Intoxicant);
        allTextFields.add(Eye);
        allTextFields.add(Ear);
        allTextFields.add(InjuryWithFainting);
        allTextFields.add(Fainting);
        allTextFields.add(Neurologist);
        allTextFields.add(Psychiatrist);
        allTextFields.add(Depression);
        allTextFields.add(Hypertension);
        allTextFields.add(HeartAttack);
        allTextFields.add(CardiacArrest);
        allTextFields.add(CardiacInsuff);
        allTextFields.add(KidneysInsuff);
        allTextFields.add(LiverInsuff);
        allTextFields.add(Diabetes);
        allTextFields.add(Thyroid);
        allTextFields.add(Lungs);
        allTextFields.add(Neurodegeneration);
        allTextFields.add(OtherDisorders);
        allTextFields.add(Alco_now);
        allTextFields.add(Alco_pa);
        allTextFields.add(Drugs);
        allTextFields.add(AgeOnset);
        allTextFields.add(AgeDiagnosis);
        allTextFields.add(DiseaseDurationY);
        allTextFields.add(MemoryComplains);
        allTextFields.add(OtherCognitiveComplains);
        allTextFields.add(SideSymptOnSet);
        allTextFields.add(CurrentSympt);
        allTextFields.add(TK_MRI);
        allTextFields.add(AsymmsymptNow);
        allTextFields.add(MotPhenot);
        allTextFields.add(UPDRSDyskin_32_33_34_35);
        allTextFields.add(UPDRSMotFluct36_37_38_39);
        allTextFields.add(UPDRSFalling_13);
        allTextFields.add(Hallucination_2);
        allTextFields.add(HallucinationOnSetY);
        allTextFields.add(Medications);
        allTextFields.add(L_Dopaequiv);
        allTextFields.add(OtherTreatment);
        allTextFields.add(Surg);
        allTextFields.add(Surg_Desc);
        allTextFields.add(ADLON);
        allTextFields.add(ADLOFF);
        allTextFields.add(IADLON);
        allTextFields.add(IADLOFF);
        allTextFields.add(HAndYON);
        allTextFields.add(HAndYOFF);
        allTextFields.add(SchAndEngON);
        allTextFields.add(SchAndEngOFF);
        allTextFields.add(UPDRSON);
        allTextFields.add(UPDRSOFF);
        allTextFields.add(UPDRSION);
        allTextFields.add(UPDRSIOFF);
        allTextFields.add(UPDRSIION);
        allTextFields.add(UPDRSIIOFF);
        allTextFields.add(UPDRSIIION);
        allTextFields.add(UPDRSIIIOFF);
        allTextFields.add(UPDRS_Speech_5);
        allTextFields.add(UPDRS_Speech_18);
        allTextFields.add(UPDRS_FacialExpress_19);
        allTextFields.add(UPDRS_TremorRest_20);
        allTextFields.add(UPDRS_EssentialTremor_21);
        allTextFields.add(UPDRS_Ridigity_22);
        allTextFields.add(UPDRS_DigitMov23);
        allTextFields.add(UPDRSIII_HandMov_24);
        allTextFields.add(UPDRSRapidAlterHandMov_25);
        allTextFields.add(UPDRSLegAgility_26);
        allTextFields.add(UPDRSArisingChair_27);
        allTextFields.add(UPDRSPosture_28);
        allTextFields.add(UPDRS_PostureStab_29);
        allTextFields.add(UPDRS_Gait_30);
        allTextFields.add(UPDRSIII_Bradykinesia_31);
        allTextFields.add(Progression_PD);
        allTextFields.add(UMSARSI);
        allTextFields.add(UMSARSII);
        allTextFields.add(UMSARSIII_Orthostatic);
        allTextFields.add(UMSARSIV);
        allTextFields.add(UMSARSI_II);
        allTextFields.add(UMSARSISpeech_1);
        allTextFields.add(UMSARSIWalking_7);
        allTextFields.add(UMSARSIFalling_8);
        allTextFields.add(UMSARSII_Facialexpression_1);
        allTextFields.add(UMSARSIISpeech_2);
        allTextFields.add(UMSARSII_OcuMotDys_3);
        allTextFields.add(UMSARSII_TremRest_4);
        allTextFields.add(UMSARSII_ActTrem_5);
        allTextFields.add(UMSARSII_IncTone_6);
        allTextFields.add(UMSARSRapidAlterMov_Hands_7);
        allTextFields.add(UMSARSFingertaps_8);
        allTextFields.add(UMSARSLegAgility_9);
        allTextFields.add(UMSARSHeelknee_10);
        allTextFields.add(UMSARSArisingChair_11);
        allTextFields.add(UMSARSPosture_12);
        allTextFields.add(UMSARSBodysway_13);
        allTextFields.add(UMSARSGait_14);
        allTextFields.add(AttentionFactACE_III);
        allTextFields.add(MemFactACE_III);
        allTextFields.add(FluencyFactACE_III);
        allTextFields.add(LangFactACE_III);
        allTextFields.add(VisualFactACE_III);
        allTextFields.add(TotalACE_III);
        allTextFields.add(TotalMini_ACE_III);
        allTextFields.add(MMSE);
        allTextFields.add(FAB12);
        allTextFields.add(BDI13_14);
        allTextFields.add(GDS9_10);
        allTextFields.add(WAIS_RPicture);
        allTextFields.add(WAIS_RPictureCent);
        allTextFields.add(CVLT_1_5);
        allTextFields.add(CVLT_1_5Sten);
        allTextFields.add(CVLT_A_1);
        allTextFields.add(CVLT_A_1Sten);
        allTextFields.add(CVLT_A_5);
        allTextFields.add(CVLT_A_5Sten);
        allTextFields.add(CVLT_B);
        allTextFields.add(CVLT_BSten);
        allTextFields.add(CVLTSTM_Free);
        allTextFields.add(CVLTSTM_FreeSten);
        allTextFields.add(CVLTSTM_Cued);
        allTextFields.add(CVLTSTM_CuedSten);
        allTextFields.add(CVLTLTM_Free);
        allTextFields.add(CVLTLTM_FreeSten);
        allTextFields.add(CVLTLTM_Cued);
        allTextFields.add(CVLTLTM_CuedSten);
        allTextFields.add(CVLTSemCluster);
        allTextFields.add(CVLTSemClustSten);
        allTextFields.add(CVLTserialClust);
        allTextFields.add(CVLTserialClustSten);
        allTextFields.add(CVLTPercentCorrectI);
        allTextFields.add(CVLTPercentCorrectISten);
        allTextFields.add(CVLTPercentCorrectII);
        allTextFields.add(CVLTPercentCorrectIISten);
        allTextFields.add(CVLTPercentCorrectIII);
        allTextFields.add(CVLTPercentCorrectIIISten);
        allTextFields.add(CVLTagreeFactor);
        allTextFields.add(CVLTagreeFactorSten);
        allTextFields.add(CVLTPERS);
        allTextFields.add(PERSSten);
        allTextFields.add(CVLTintrusFree);
        allTextFields.add(CVLTintrusFreeSten);
        allTextFields.add(CVLTintrusCues);
        allTextFields.add(CVLTintrusCuesSten);
        allTextFields.add(CVLT_RecogTotal);
        allTextFields.add(CVLT_RecogTotalSten);
        allTextFields.add(CVLT_Differentiation);
        allTextFields.add(CVLT_DifferentiationSten);
        allTextFields.add(CVLT_ErrorRecog);
        allTextFields.add(CVLT_ErrorRecogSten);
        allTextFields.add(TMT_A);
        allTextFields.add(TMT_Acent);
        allTextFields.add(TMT_A_errors);
        allTextFields.add(TMT_B);
        allTextFields.add(TMT_Bcent);
        allTextFields.add(TMT_B_errors);
        allTextFields.add(Rythymtest_ABC);
        allTextFields.add(Rythymtest_ABCranga);
        allTextFields.add(TOL_TotalCorrect);
        allTextFields.add(TOL_TotalCorrectCent);
        allTextFields.add(TOL_TotalMoveScore);
        allTextFields.add(TOL_TotalMoveScoreCent);
        allTextFields.add(TOL_TotalInitTime);
        allTextFields.add(TOL_TotalInitTimeCent);
        allTextFields.add(TOL_TotalExecutTime);
        allTextFields.add(TOL_TotalExecutTimeCent);
        allTextFields.add(TOL_TotalTime);
        allTextFields.add(TOL_TotalTimeCent);
        allTextFields.add(FluencyKraw);
        allTextFields.add(FluencyAnimalsRaw);
        allTextFields.add(FluencySharpsRaw);
        allTextFields.add(BNTTotalScore);
        allTextFields.add(BNTCorrectPhonemCues);
        allTextFields.add(BNTCorrectSemantCues);
        allTextFields.add(BNTCorrectContextCues);
        allTextFields.add(BNTTotalTime);
        allTextFields.add(CLOX1Draw);
        allTextFields.add(CLOX2Copy);
        allTextFields.add(RBMTShortDelay);
        allTextFields.add(RBMTShortDelayCent);
        allTextFields.add(RBMTLongDelay);
        allTextFields.add(RBMTLongDelayCent);
        allTextFields.add(GONOGOProcentInCorrGO);
        allTextFields.add(GONOGOProcentInCorrNOGO);
        allTextFields.add(GONOGONrInCorrGO);
        allTextFields.add(GONOGONrInCorrNOGO);
        allTextFields.add(GONOGONrCorrectGO);
        allTextFields.add(GONOGONrCorrectNOGO);
        allTextFields.add(MeanResponseTimeCorrrectGO);
        allTextFields.add(ElevatorCountTotal);
        allTextFields.add(ElevatorCountTotalCent);
        allTextFields.add(ElevatorDistractTotal);
        allTextFields.add(ElevatorDistractTotalCent);
        allTextFields.add(WCSTLPP);
        allTextFields.add(WCSTLPO);
        allTextFields.add(WCSTLBO);
        allTextFields.add(WCST_LBOcent);
        allTextFields.add(WCSTPB);
        allTextFields.add(WCSTOP);
        allTextFields.add(WCSTOPcent);
        allTextFields.add(WCSTPOP);
        allTextFields.add(WCSTBP);
        allTextFields.add(WCSTBPcent);
        allTextFields.add(WCSTPBP);
        allTextFields.add(WCSTPBPcent);
        allTextFields.add(WCSTBN);
        allTextFields.add(WCSTBNcent);
        allTextFields.add(WCSTPBN);
        allTextFields.add(WCSTODP);
        allTextFields.add(WCSTPODP);
        allTextFields.add(WCSTPODPcent);
        allTextFields.add(WCSTLZK);
        allTextFields.add(WCSTPPMZ);
        allTextFields.add(WCSTPUN);
        allTextFields.add(WCSTUU);
        allTextFields.add(Similar_WAISTotal);
        allTextFields.add(Similar_WAISCent);
        allTextFields.add(WAIS_Info);
        allTextFields.add(WAIS_Info_Cent);
        allTextFields.add(WAIS_DigitSpan);
        allTextFields.add(WAIS_DigitSpan_Cent);
        allTextFields.add(MirrorTotalTime);
        allTextFields.add(MirrorMeanTime);
        allTextFields.add(MirrorCorrectScore);
        allTextFields.add(MirrorErrors);
        allTextFields.add(MirrorCorrectedErrors);
        allTextFields.add(JLOCorrect);
        allTextFields.add(JLOWP);
        allTextFields.add(JLOcent);
    }
    private PatientInfoEntity getPatient(){
        PatientInfoEntity patient = new PatientInfoEntity();

        patient.setName(Name.getText());
        patient.setSubjectCode(SubjectCode.getText());
        patient.setIdNumber(IDNumber.getText());
        patient.setPhone(Phone.getText());
//        patient.setDateTest(java.sql.Date.valueOf(DateTest.getText()));
//        patient.setBirthdate(java.sql.Date.valueOf(Birthdate.getText()));
//        patient.setAge(Integer.parseInt(Age.getText()));
//        patient.setGr(Integer.parseInt(Gr.getText()));
//        patient.setSex(Integer.parseInt(Sex.getText()));
//        patient.setBac(Integer.parseInt(Bac.getText()));
//        patient.setEdu(Integer.parseInt(Edu.getText()));
//        patient.setEduY(Integer.parseInt(EduY.getText()));
//        patient.setMusEdu(Integer.parseInt(MusEdu.getText()));
//        patient.setMusEduY(Integer.valueOf(MusEduY.getText()));
//        patient.setHand(Integer.valueOf(Hand.getText()));
//        patient.setProfession(Profession.getText());
//        patient.setCurrentWork(CurrentWork.getText());
//        patient.setIntoxicant(Integer.valueOf(Intoxicant.getText()));
//        patient.setEye(Integer.valueOf(Eye.getText()));
//        patient.setEar(Integer.valueOf(Ear.getText()));
//        patient.setInjuryWithFainting(Integer.valueOf(InjuryWithFainting.getText()));
//        patient.setFainting(Integer.valueOf(Fainting.getText()));


        System.out.println(patient.toString());
        return patient;
    }
    private boolean idNumberVerification() {
        if (IDNumber.getText().length() != 11){
            Platform.runLater(() -> {
                Stage primaryStage = new Stage();
                primaryStage.setTitle("Fail");
                Label label = new Label("Check your pesel!");
                StackPane root = new StackPane();
                root.getChildren().add(label);
                primaryStage.setScene(new Scene(root, 300, 250));
                primaryStage.show();
            });
            return false;
        }
        return true;
    }

    public static void main(String[] args) throws Exception {
        Class curClass = PatientInfoEntity.class;
        Method[] allMethods = curClass.getMethods();
        List<Method> setters = new ArrayList<Method>();
        for(Method method : allMethods) {
            if(method.getName().startsWith("set")) {
                setters.add(method);
            }
        }
        for (Method setter : setters){
        }
    }
}

